/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as Aula01RouteImport } from './routes/aula-01'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AvaliacaoRouteImport } from './routes/avaliacao'
import { Route as BibliografiaRouteImport } from './routes/bibliografia'
import { Route as EntregasRouteImport } from './routes/entregas'
import { Route as MetodologiaRouteImport } from './routes/metodologia'
import { Route as PlanoRouteImport } from './routes/plano'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as EncontrosIndexRouteImport } from './routes/encontros.index'
import { Route as EncontrosNumeroRouteImport } from './routes/encontros.$numero'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const Aula01Route = Aula01RouteImport.update({
  id: '/aula-01',
  path: '/aula-01',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AvaliacaoRoute = AvaliacaoRouteImport.update({
  id: '/avaliacao',
  path: '/avaliacao',
  getParentRoute: () => rootRouteImport,
} as any)
const BibliografiaRoute = BibliografiaRouteImport.update({
  id: '/bibliografia',
  path: '/bibliografia',
  getParentRoute: () => rootRouteImport,
} as any)
const EntregasRoute = EntregasRouteImport.update({
  id: '/entregas',
  path: '/entregas',
  getParentRoute: () => rootRouteImport,
} as any)
const MetodologiaRoute = MetodologiaRouteImport.update({
  id: '/metodologia',
  path: '/metodologia',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanoRoute = PlanoRouteImport.update({
  id: '/plano',
  path: '/plano',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const EncontrosIndexRoute = EncontrosIndexRouteImport.update({
  id: '/encontros/',
  path: '/encontros/',
  getParentRoute: () => rootRouteImport,
} as any)
const EncontrosNumeroRoute = EncontrosNumeroRouteImport.update({
  id: '/encontros/$numero',
  path: '/encontros/$numero',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aula-01': typeof Aula01Route
  '/auth': typeof AuthRoute
  '/avaliacao': typeof AvaliacaoRoute
  '/bibliografia': typeof BibliografiaRoute
  '/entregas': typeof EntregasRoute
  '/metodologia': typeof MetodologiaRoute
  '/plano': typeof PlanoRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/encontros/$numero': typeof EncontrosNumeroRoute
  '/encontros/': typeof EncontrosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aula-01': typeof Aula01Route
  '/auth': typeof AuthRoute
  '/avaliacao': typeof AvaliacaoRoute
  '/bibliografia': typeof BibliografiaRoute
  '/entregas': typeof EntregasRoute
  '/metodologia': typeof MetodologiaRoute
  '/plano': typeof PlanoRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/encontros/$numero': typeof EncontrosNumeroRoute
  '/encontros': typeof EncontrosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/aula-01': typeof Aula01Route
  '/auth': typeof AuthRoute
  '/avaliacao': typeof AvaliacaoRoute
  '/bibliografia': typeof BibliografiaRoute
  '/entregas': typeof EntregasRoute
  '/metodologia': typeof MetodologiaRoute
  '/plano': typeof PlanoRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/encontros/$numero': typeof EncontrosNumeroRoute
  '/encontros/': typeof EncontrosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aula-01'
    | '/auth'
    | '/avaliacao'
    | '/bibliografia'
    | '/entregas'
    | '/metodologia'
    | '/plano'
    | '/admin'
    | '/encontros/$numero'
    | '/encontros/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aula-01'
    | '/auth'
    | '/avaliacao'
    | '/bibliografia'
    | '/entregas'
    | '/metodologia'
    | '/plano'
    | '/admin'
    | '/encontros/$numero'
    | '/encontros'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/aula-01'
    | '/auth'
    | '/avaliacao'
    | '/bibliografia'
    | '/entregas'
    | '/metodologia'
    | '/plano'
    | '/_authenticated/admin'
    | '/encontros/$numero'
    | '/encontros/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  Aula01Route: typeof Aula01Route
  AuthRoute: typeof AuthRoute
  AvaliacaoRoute: typeof AvaliacaoRoute
  BibliografiaRoute: typeof BibliografiaRoute
  EntregasRoute: typeof EntregasRoute
  MetodologiaRoute: typeof MetodologiaRoute
  PlanoRoute: typeof PlanoRoute
  EncontrosNumeroRoute: typeof EncontrosNumeroRoute
  EncontrosIndexRoute: typeof EncontrosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aula-01': {
      id: '/aula-01'
      path: '/aula-01'
      fullPath: '/aula-01'
      preLoaderRoute: typeof Aula01RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/avaliacao': {
      id: '/avaliacao'
      path: '/avaliacao'
      fullPath: '/avaliacao'
      preLoaderRoute: typeof AvaliacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bibliografia': {
      id: '/bibliografia'
      path: '/bibliografia'
      fullPath: '/bibliografia'
      preLoaderRoute: typeof BibliografiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entregas': {
      id: '/entregas'
      path: '/entregas'
      fullPath: '/entregas'
      preLoaderRoute: typeof EntregasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metodologia': {
      id: '/metodologia'
      path: '/metodologia'
      fullPath: '/metodologia'
      preLoaderRoute: typeof MetodologiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plano': {
      id: '/plano'
      path: '/plano'
      fullPath: '/plano'
      preLoaderRoute: typeof PlanoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/encontros/': {
      id: '/encontros/'
      path: '/encontros'
      fullPath: '/encontros/'
      preLoaderRoute: typeof EncontrosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/encontros/$numero': {
      id: '/encontros/$numero'
      path: '/encontros/$numero'
      fullPath: '/encontros/$numero'
      preLoaderRoute: typeof EncontrosNumeroRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  Aula01Route: Aula01Route,
  AuthRoute: AuthRoute,
  AvaliacaoRoute: AvaliacaoRoute,
  BibliografiaRoute: BibliografiaRoute,
  EntregasRoute: EntregasRoute,
  MetodologiaRoute: MetodologiaRoute,
  PlanoRoute: PlanoRoute,
  EncontrosNumeroRoute: EncontrosNumeroRoute,
  EncontrosIndexRoute: EncontrosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
